apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: bf3-server-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bf3-server-kube
  template:
    metadata:
      labels:
        app: bf3-server-kube
    spec:
      containers:
      - image: 10.105.68.53:5000/bf3_server:latest
        name: bf3-server-kube
        ports:
          - containerPort: 3333
      imagePullSecrets:
        - name: registrypullsecret
      tolerations:
        - key: node-type
          value: production-node
          effect: NoSchedule


