apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC4xMDUuNjguNTM6NTAwMCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZjbVZuYVhOMGNuaz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson