CREATE DATABASE CHAT_APPLICATION;

USE CHAT_APPLICATION;

CREATE TABLE USER
(
USER_ID INT NOT NULL AUTO_INCREMENT,
USER_FULLNAME VARCHAR(30) NOT NULL,
USER_USERNAME VARCHAR(15) NOT NULL,
USER_PASSWORD VARCHAR(64) NOT NULL,
USER_COLOR INT NOT NULL CHECK (USER_COLOR>=30 AND USER_COLOR<=39),
USER_STATUS BOOLEAN NOT NULL,
USER_TIMESTAMP TIMESTAMP,
CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);

CREATE TABLE ROOM
(
ROOM_ID INT NOT NULL AUTO_INCREMENT,
ROOM_NAME VARCHAR(30) NOT NULL,
ROOM_TYPE BOOLEAN NOT NULL,
ROOM_TIMESTAMP TIMESTAMP,
CONSTRAINT PK_ROOM PRIMARY KEY (ROOM_ID)
);

CREATE TABLE MSG
(
MSG_ID INT NOT NULL AUTO_INCREMENT,
MSG_CONTENT LONGTEXT,
USER_ID INT,
ROOM_ID INT,
MSG_TIMESTAMP TIMESTAMP,
CONSTRAINT PK_MSG PRIMARY KEY (MSG_ID)
);

CREATE TABLE REGISTRATION
(
REG_ID INT NOT NULL AUTO_INCREMENT,
ROOM_ID INT,
USER_ID INT,
REG_TIMESTAMP TIMESTAMP,
CONSTRAINT PK_REG PRIMARY KEY (REG_ID)
);

ALTER TABLE MSG ADD CONSTRAINT FK01_MSG FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE MSG ADD CONSTRAINT FK02_MSG FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);

ALTER TABLE REGISTRATION ADD CONSTRAINT FK01_REG FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE REGISTRATION ADD CONSTRAINT FK02_REG FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);

# PASSWORD=1
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('ADMIN', 'ADMIN', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 31, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Binh Thanh Nguyen', 'binh.t.nguyen', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 37, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Co Minh Huynh', 'co.m.huynh', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 37, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Phat Tan Phung', 'phat.t.p', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 37, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Anh Tuan Nguyen', 'anh.t.nguyen', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 37, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Y Ngoc Hiep Huynh', 'y.nh.huynh', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 37, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Duong Dang Trinh', 'duong.d.trinh', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 37, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Khang Lam', 'khangl', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 32, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Quang Xuan Nhat Nghiem', 'quangnxn', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 34, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Uyen Pham Hoai Le', 'uyen.ph.le', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 33, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Hiep Phuc Thai', 'hiep.p.thai', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 36, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Khuong Dinh Nguyen', 'khuong.d.nguyen', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 33, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Man Hue Phan', 'man.h.phan', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 35, FALSE);
INSERT INTO USER (USER_FULLNAME, USER_USERNAME, USER_PASSWORD, USER_COLOR, USER_STATUS) VALUES ('Thong Tien Lam Phan', 'thong.tl.phan', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', 35, FALSE);

INSERT INTO ROOM (ROOM_NAME, ROOM_TYPE) VALUES ('INTERNSHIP SEASON 34 - SUPPORT', TRUE);
INSERT INTO ROOM (ROOM_NAME, ROOM_TYPE) VALUES ('BF3 Official - CBA Inter S34', TRUE);

# ROOM INTERSHIP SEASON 31 - SUPPORT
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 1);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 2);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 3);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 4);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 5);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 6);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 7);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 8);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 9);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 10);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 11);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 12);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 13);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (1, 14);

# ROOM BF3 OFFICIAL - CBA INTERNSHIP SEASON 34
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 1);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 2);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 3);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 4);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 5);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 6);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 7);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 8);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 9);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 10);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 11);
INSERT INTO REGISTRATION (ROOM_ID, USER_ID) VALUES (2, 12);

# MSG IN ROOM INTERSHIP SEASON 31 - SUPPORT
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Hey guys', 13, 1);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('I just saw someone accidentally lost the timesheet registration of EMB Team', 13, 1);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('I have just returned it, you guys please access the timesheet to fill it in again huh?', 13, 1);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Good morning everybody!', 13, 1);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Good morning!', 6, 1);

# MSG IN ROOM BF3 OFFICIAL - CBA INTERNSHIP SEASON 34
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Again, remember to schedule your presentation this week!', 8, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Lets do your presentation at 10:30 am on Friday like last time!', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('All members of my team must be present at the presentation, right?', 7, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Yes, of course', 8, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('I think your team should present at 10:30 on Friday 18th November', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('And then hold a retrospective meeting the next Monday', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Thanks for your advice, the team will schedule it like that', 7, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('OK!', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('OMG What a great news!', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('So whats new?', 8, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('There will be 3 LM attending your group presentation!!', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Good luck to you', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Wow ...', 4, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Quite happy, congratulations and good luck', 10, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Dont worry, LM wont be too demanding with an internship position', 11, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Hi! Do you guys have any issues that need to be solved these days?', 9, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Yes, and of course, there are many', 2, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('What about server connection errors?', 9, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Yes', 5, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Yes, about that error, we have already fixed it', 6, 2);
INSERT INTO MSG (MSG_CONTENT, USER_ID, ROOM_ID) VALUES ('Working time is up, you guys go home, lets deal with the problems tomorrow', 8, 2);